//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEmpleados.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionEmpleados.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string AddButon {
            get {
                return ResourceManager.GetString("AddButon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to close the application?.
        /// </summary>
        public static string CloseMessage {
            get {
                return ResourceManager.GetString("CloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this department?.
        /// </summary>
        public static string DeleteDepartmentConfirmation {
            get {
                return ResourceManager.GetString("DeleteDepartmentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this employee?.
        /// </summary>
        public static string DeleteEmployeeConfirmation {
            get {
                return ResourceManager.GetString("DeleteEmployeeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Department successfully deleted.
        /// </summary>
        public static string DepartmentDeleted {
            get {
                return ResourceManager.GetString("DepartmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A department with this name already exists..
        /// </summary>
        public static string DepartmentDuplicated {
            get {
                return ResourceManager.GetString("DepartmentDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departments.
        /// </summary>
        public static string DepartmentMenu {
            get {
                return ResourceManager.GetString("DepartmentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Department Name.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Department.
        /// </summary>
        public static string DepartmentText {
            get {
                return ResourceManager.GetString("DepartmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        public static string DniText {
            get {
                return ResourceManager.GetString("DniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This DNI already belongs to an Employee.
        /// </summary>
        public static string DuplicatedDni {
            get {
                return ResourceManager.GetString("DuplicatedDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employee successfully deleted.
        /// </summary>
        public static string EmployeeDeleted {
            get {
                return ResourceManager.GetString("EmployeeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The DNI must have a valid format..
        /// </summary>
        public static string EmployeeDniEmpty {
            get {
                return ResourceManager.GetString("EmployeeDniEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email must have a valid format..
        /// </summary>
        public static string EmployeeEmailEmpty {
            get {
                return ResourceManager.GetString("EmployeeEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employees.
        /// </summary>
        public static string EmployeeMenu {
            get {
                return ResourceManager.GetString("EmployeeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The employee must have a name..
        /// </summary>
        public static string EmployeeNameEmpty {
            get {
                return ResourceManager.GetString("EmployeeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Employees.
        /// </summary>
        public static string EmployeeNumber {
            get {
                return ResourceManager.GetString("EmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The phone number must have a valid format (9 digits)..
        /// </summary>
        public static string EmployeePhoneEmpty {
            get {
                return ResourceManager.GetString("EmployeePhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The position cannot be empty..
        /// </summary>
        public static string EmployeePositionEmpty {
            get {
                return ResourceManager.GetString("EmployeePositionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employee updated successfully.
        /// </summary>
        public static string EmployeeUpdated {
            get {
                return ResourceManager.GetString("EmployeeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string EnglishLenguage {
            get {
                return ResourceManager.GetString("EnglishLenguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graph.
        /// </summary>
        public static string GraphMenu {
            get {
                return ResourceManager.GetString("GraphMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Files.
        /// </summary>
        public static string ImageFiles {
            get {
                return ResourceManager.GetString("ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguage.
        /// </summary>
        public static string LenguageText {
            get {
                return ResourceManager.GetString("LenguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string NewButton {
            get {
                return ResourceManager.GetString("NewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A department must have a name.
        /// </summary>
        public static string NewDepartmentError {
            get {
                return ResourceManager.GetString("NewDepartmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Department has been saved successfully.
        /// </summary>
        public static string NewDepartmentSaved {
            get {
                return ResourceManager.GetString("NewDepartmentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employee Error.
        /// </summary>
        public static string NewEmployeeError {
            get {
                return ResourceManager.GetString("NewEmployeeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The employee has been saved successfully.
        /// </summary>
        public static string NewEmployeeSaved {
            get {
                return ResourceManager.GetString("NewEmployeeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        public static string NoneDepartment {
            get {
                return ResourceManager.GetString("NoneDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Number.
        /// </summary>
        public static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove the employee from this department?.
        /// </summary>
        public static string RemoveEmployeeFromDepartment {
            get {
                return ResourceManager.GetString("RemoveEmployeeFromDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings saved successfully. Please restart the application to see the changes..
        /// </summary>
        public static string SaveSettingsText {
            get {
                return ResourceManager.GetString("SaveSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string SearchFilter {
            get {
                return ResourceManager.GetString("SearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a File.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string SpanishLenguage {
            get {
                return ResourceManager.GetString("SpanishLenguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DAM Proyect for Employees Managment.
        /// </summary>
        public static string SubTitleHome {
            get {
                return ResourceManager.GetString("SubTitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theme.
        /// </summary>
        public static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GestioDam.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work Position.
        /// </summary>
        public static string WorkText {
            get {
                return ResourceManager.GetString("WorkText", resourceCulture);
            }
        }
    }
}
